# Generated by Django 4.2.4 on 2023-08-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
